# train
training:
  lr: 3e-5
  epochs: 60

leomix:
  mode: [train]
  dataset: LeoMix
  mix: [sitrscan_qa, sitrscan_cap, rscan_qa, scene_cap]
  #mix: [cliport]
  ratio: 1.0
  dataset_wrapper: LeoObjPadDatasetWrapper
  dataset_wrapper_args: ${dataset_wrapper_args}
  train_dataloader_args: ${dataloader.train}
  eval_dataloader_args: ${dataloader.eval}

#mix: [sitrscan_qa, sitrscan_cap, rscan_qa, scene_cap]
# [sitrscan_cap, sitrscan_qa, sitrscan_afford, sitrscan_planning]

# eval

# scene_cap:
#   mode: [test]
#   dataset: LeoSceneCap
#   dataset_wrapper: LeoObjPadDatasetWrapper
#   dataset_wrapper_args: ${dataset_wrapper_args}
#   eval_dataloader_args: ${dataloader.eval}
#   evaluator: CaptionEvaluator

# scan2cap:
#   mode: [val,test]
#   dataset: LeoScan2Cap
#   dataset_wrapper: LeoObjPadDatasetWrapper
#   dataset_wrapper_args: ${dataset_wrapper_args}
#   eval_dataloader_args: ${dataloader.eval}
#   evaluator: CaptionEvaluator

# scanqa:
#   mode: [val, test]
#   dataset: LeoScanQA
#   dataset_wrapper: LeoObjPadDatasetWrapper
#   dataset_wrapper_args: ${dataset_wrapper_args}
#   eval_dataloader_args: ${dataloader.eval}
#   evaluator: ScanQAEvaluator

# sqa3d:
#   mode: [val, test]
#   dataset: LeoSQA3D
#   dataset_wrapper: LeoObjPadDatasetWrapper
#   dataset_wrapper_args: ${dataset_wrapper_args}
#   eval_dataloader_args: ${dataloader.eval}
#   evaluator: SQA3DEvaluator



# sitrscan_qa:
#   mode: [val,test]
#   dataset: Spartun3RScanSitQA
#   dataset_wrapper: LeoObjPadDatasetWrapper
#   dataset_wrapper_args: ${dataset_wrapper_args}
#   eval_dataloader_args: ${dataloader.eval}
#   evaluator: ScanQAEvaluator



# sitrscan_afford:
#   mode: [val]
#   dataset: Spartun3RScanAfford
#   dataset_wrapper: LeoObjPadDatasetWrapper
#   dataset_wrapper_args: ${dataset_wrapper_args}
#   eval_dataloader_args: ${dataloader.eval}
#   evaluator: CaptionEvaluator

# sitrscan_planning:
#   mode: [val]
#   dataset: Spartun3RScanPlanning
#   dataset_wrapper: LeoObjPadDatasetWrapper
#   dataset_wrapper_args: ${dataset_wrapper_args}
#   eval_dataloader_args: ${dataloader.eval}
#   evaluator: CaptionEvaluator


sitrscan_cap:
  mode: [val]
  dataset: Spartun3RScanSitCap
  dataset_wrapper: LeoObjPadDatasetWrapper
  dataset_wrapper_args: ${dataset_wrapper_args}
  eval_dataloader_args: ${dataloader.eval}
  evaluator: CaptionEvaluator

# mp3d_objnav:
#   mode: [val]   # offline test
#   dataset: LeoMP3DObjNav
#   dataset_wrapper: LeoObjPadDatasetWrapper
#   dataset_wrapper_args: ${dataset_wrapper_args}
#   eval_dataloader_args: ${dataloader.eval}
#   evaluator: ObjNavEvaluator

